---
- name: Install required packages
  yum:
    name:
      - wget
      - curl
      - tar
      - gpg
    state: present

- name: Create Prometheus directory
  file:
    path: /etc/prometheus
    state: directory
    mode: '0755'

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.54.1/prometheus-2.54.1.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: Move Prometheus binary to /usr/local/bin
  command: mv /usr/local/bin/prometheus-2.54.1.linux-amd64/prometheus /usr/local/bin/prometheus

- name: Move Prometheus configuration file to /etc/prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

- name: Create Prometheus service file
  copy:
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=root
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --web.listen-address="0.0.0.0:9090"

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/prometheus.service

- name: Start and enable Prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
